/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.unix.utility.area;

import simple.api.ClientContext;
import simple.api.coords.WorldArea;
import simple.api.coords.WorldPoint;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author 0x181
 */
public class AreaGen extends JFrame implements ActionListener {

    /**
     * Creates new form AreaGen
     */
    public AreaGen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        jPanel1 = new JPanel();
        txt_LocA = new JLabel();
        btn_SetA = new JButton();
        txt_LocB = new JLabel();
        btn_SetB = new JButton();
        txt_Out = new JTextField();
        btn_Gen = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Area Generator");
        setResizable(false);
        setAlwaysOnTop(true);

        jLabel1.setText("Welcome to the Area Creator");

        jPanel1.setBorder(BorderFactory.createEtchedBorder());
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentHidden(evt);
            }
        });

        txt_LocA.setText("Location A:");

        btn_SetA.setText("Set");
        btn_SetA.addActionListener(this);

        txt_LocB.setText("Location B:");

        btn_SetB.setText("Set");
        btn_SetB.addActionListener(this);

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(btn_SetB, GroupLayout.PREFERRED_SIZE, 53, GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_LocA, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_SetA, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txt_LocB))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_LocA)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_SetA)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_LocB)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_SetB)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        txt_Out.setText("jTextField1");

        btn_Gen.setText("Generate");
        btn_Gen.addActionListener(this);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_Gen)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_Out, GroupLayout.PREFERRED_SIZE, 186, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Out, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Gen))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1ComponentHidden


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btn_Gen;
    private JButton btn_SetA;
    private JButton btn_SetB;
    private JLabel jLabel1;
    private JLabel txt_LocA;
    private JLabel txt_LocB;
    private JPanel jPanel1;
    private JTextField txt_Out;

    @Override
    public void actionPerformed(ActionEvent e) {
        Object o = e.getSource();
        ClientContext c = ClientContext.instance();
        if (o.equals(btn_SetA)) {
            txt_LocA.setText("Location A: " + c.players.getLocal().getLocation().x + ", " + c.players.getLocal().getLocation().y + ", " + c.players.getLocal().getLocation().plane);
        } else if (o.equals(btn_SetB)) {
            txt_LocB.setText("Location B: " + c.players.getLocal().getLocation().x + ", " + c.players.getLocal().getLocation().y + ", " + c.players.getLocal().getLocation().plane);
        } else if (o.equals(btn_Gen)) {
            String rawA = txt_LocA.getText().substring(12);
            System.out.println("RawA: " + rawA);
            String rawB = txt_LocB.getText().substring(12);
            System.out.println("RawB: " + rawB);
            txt_Out.setText("public WorldArea myArea = new WorldArea(new WorldPoint(" + rawA + "), new WorldPoint(" + rawB + "));");
        }

    }
    // End of variables declaration//GEN-END:variables
}
