/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.unix.script.ui;

import org.unix.script.manager.ScriptManager;
import org.unix.script.manager.Vars;
import org.unix.script.tasks.Condition;
import simple.api.ClientContext;
import simple.api.coords.WorldArea;
import simple.api.coords.WorldPoint;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author 0x181
 */
public class ui_Conditional extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form ui_Conditional
     */
    public ui_Conditional() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_AddLoc = new javax.swing.JButton();
        in_Location = new javax.swing.JTextField();
        btn_GrabLocation = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbo_AreaSelect = new javax.swing.JComboBox<>();
        rad_OutsideArea = new javax.swing.JRadioButton();
        rad_InsideArea = new javax.swing.JRadioButton();
        btn_AddArea = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_InvFull = new javax.swing.JButton();
        btn_InvEmpty = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        in_InvMissItemName = new javax.swing.JTextField();
        btn_AddInvMiss = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        in_InvAmtName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        in_InvAmtQuantity = new javax.swing.JTextField();
        btn_AddInvAmt = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        in_InterfaceId = new javax.swing.JTextField();
        rad_InterfaceOpen = new javax.swing.JRadioButton();
        rad_InterfaceClosed = new javax.swing.JRadioButton();
        btn_AddInterface = new javax.swing.JButton();
        btn_InterfaceCurrent = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        in_AnimID = new javax.swing.JTextField();
        btn_AnimCurrent = new javax.swing.JButton();
        btn_AddAnimation = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btn_InCombat = new javax.swing.JButton();
        btn_LowHP = new javax.swing.JButton();
        btn_LowPrayer = new javax.swing.JButton();
        btn_NoCombat = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        in_ChatMessage = new javax.swing.JTextField();
        btn_AddChatMessage = new javax.swing.JButton();
        chx_RepeatLastTask = new javax.swing.JCheckBox();
        areaComboModel = new DefaultComboBoxModel();

        rad_InsideArea.setEnabled(true);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("We should probably wait here...");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("until Location Equals:");

        btn_AddLoc.setText("Add Location Condition");
        btn_AddLoc.addActionListener(this);

        in_Location.setEditable(false);
        in_Location.setText("");

        btn_GrabLocation.setText("Get Current Location");
        btn_GrabLocation.addActionListener(this);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_GrabLocation)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(in_Location, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(280, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_AddLoc)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(in_Location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_GrabLocation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(btn_AddLoc)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Location", jPanel1);

        jLabel3.setText("Selected Area:");

        cbo_AreaSelect.setModel(areaComboModel);
        for(String s : ScriptManager.getAreasByName()) {
            areaComboModel.addElement(s);
        }
        cbo_AreaSelect.updateUI();

        rad_OutsideArea.setText("Outside Area");
        rad_OutsideArea.addActionListener(this);

        rad_InsideArea.setText("Within Area");
        rad_InsideArea.addActionListener(this);

        btn_AddArea.setText("Add Area Condition");
        btn_AddArea.addActionListener(this);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbo_AreaSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rad_OutsideArea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rad_InsideArea)))
                .addContainerGap(309, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_AddArea))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbo_AreaSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rad_OutsideArea)
                    .addComponent(rad_InsideArea))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(btn_AddArea)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Area", jPanel2);

        btn_InvFull.setText("Inventory Full");
        btn_InvFull.addActionListener(this);

        btn_InvEmpty.setText("Inventory Empty");
        btn_InvEmpty.addActionListener(this);

        jLabel4.setText("Missing Item:");

        in_InvMissItemName.setText("");

        btn_AddInvMiss.setText("Add Missing Item Condition");
        btn_AddInvMiss.addActionListener(this);

        jLabel5.setText("Item name:");

        in_InvAmtName.setText("");

        jLabel6.setText("Quantity:");

        in_InvAmtQuantity.setText("");

        btn_AddInvAmt.setText("Add Item Quantity Condition");
        btn_AddInvAmt.addActionListener(this);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_InvFull)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_InvEmpty)
                                .addGap(0, 286, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(in_InvMissItemName))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(in_InvAmtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(in_InvAmtName)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_AddInvMiss, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_AddInvAmt, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_InvFull)
                    .addComponent(btn_InvEmpty))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(in_InvMissItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_AddInvMiss)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(in_InvAmtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(in_InvAmtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_AddInvAmt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inventory", jPanel3);

        jLabel7.setText("Interface ID:");

        in_InterfaceId.setText("");

        rad_InterfaceOpen.setText("Open");
        rad_InterfaceOpen.addActionListener(this);

        rad_InterfaceClosed.setText("Closed");
        rad_InterfaceClosed.addActionListener(this);

        btn_AddInterface.setText("Add Interface Condition");
        btn_AddInterface.addActionListener(this);

        btn_InterfaceCurrent.setText("Get Current");
        btn_InterfaceCurrent.addActionListener(this);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_AddInterface)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_InterfaceCurrent)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(in_InterfaceId, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rad_InterfaceOpen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rad_InterfaceClosed)
                .addContainerGap(203, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(in_InterfaceId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rad_InterfaceOpen)
                    .addComponent(rad_InterfaceClosed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_InterfaceCurrent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(btn_AddInterface)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Interface", jPanel4);

        jLabel9.setText("Animation ID:");

        in_AnimID.setText("jTextField1");

        btn_AnimCurrent.setText("Get Current");

        btn_AddAnimation.setText("Add Animation Condition");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_AddAnimation)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(in_AnimID, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(314, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(116, 116, 116)
                    .addComponent(btn_AnimCurrent)
                    .addContainerGap(316, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(in_AnimID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addComponent(btn_AddAnimation)
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(btn_AnimCurrent)
                    .addContainerGap(158, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Animation", jPanel5);

        btn_InCombat.setText("In Combat");

        btn_LowHP.setText("Low HP (<30%)");

        btn_LowPrayer.setText("Low Prayer (<30%)");

        btn_NoCombat.setText("Out of Combat");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_InCombat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_LowHP, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                    .addComponent(btn_LowPrayer)
                    .addComponent(btn_NoCombat, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(388, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_InCombat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_LowHP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_LowPrayer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_NoCombat)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Combat", jPanel6);

        jLabel8.setText("Enter Chat Message:");

        in_ChatMessage.setText("jTextField1");

        btn_AddChatMessage.setText("Add Chat Message Condition");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(in_ChatMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_AddChatMessage)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(in_ChatMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(btn_AddChatMessage))
        );

        jTabbedPane1.addTab("Chat Message", jPanel7);

        chx_RepeatLastTask.setText("Repeat Last Task");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chx_RepeatLastTask)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chx_RepeatLastTask, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AddAnimation;
    private javax.swing.JButton btn_AddArea;
    private javax.swing.JButton btn_AddChatMessage;
    private javax.swing.JButton btn_AddInterface;
    private javax.swing.JButton btn_AddInvAmt;
    private javax.swing.JButton btn_AddInvMiss;
    private javax.swing.JButton btn_AddLoc;
    private javax.swing.JButton btn_AnimCurrent;
    private javax.swing.JButton btn_InCombat;
    private javax.swing.JButton btn_InterfaceCurrent;
    private javax.swing.JButton btn_InvEmpty;
    private javax.swing.JButton btn_InvFull;
    private javax.swing.JButton btn_LowHP;
    private javax.swing.JButton btn_LowPrayer;
    private javax.swing.JButton btn_NoCombat;
    private javax.swing.JComboBox<String> cbo_AreaSelect;
    private javax.swing.JCheckBox chx_RepeatLastTask;
    private javax.swing.JTextField in_AnimID;
    private javax.swing.JTextField in_ChatMessage;
    private javax.swing.JTextField in_InterfaceId;
    private javax.swing.JTextField in_InvAmtName;
    private javax.swing.JTextField in_InvAmtQuantity;
    private javax.swing.JTextField in_InvMissItemName;
    private javax.swing.JTextField in_Location;
    private javax.swing.JButton btn_GrabLocation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rad_InsideArea;
    private javax.swing.JRadioButton rad_InterfaceClosed;
    private javax.swing.JRadioButton rad_InterfaceOpen;
    private javax.swing.JRadioButton rad_OutsideArea;
    private DefaultComboBoxModel areaComboModel;

    @Override
    public void actionPerformed(ActionEvent e) {
        Object o = e.getSource();
        ClientContext c = ClientContext.instance();
        WorldPoint loc = c.players.getLocal().getLocation();

        if (o.equals(btn_GrabLocation)) {
            in_Location.setText("" + loc.x + ", " + loc.y + ", " + loc.plane);
            in_Location.updateUI();
        }

        if (o.equals(btn_AddLoc)) {
            if (in_Location.getText().isEmpty()) {return;}
            int x = Integer.parseInt(in_Location.getText().split(", ")[0]);
            int y = Integer.parseInt(in_Location.getText().split(", ")[1]);
            int h = Integer.parseInt(in_Location.getText().split(", ")[2]);
            ScriptManager.addTask(new Condition.Location(new WorldPoint(x, y, h), chx_RepeatLastTask.isSelected()));
            SetupUI.taskListModel.addElement("[COND] <Loc> " + x + ", " + y + ", " + h);
            SetupUI.list_Tasks.updateUI();
            SetupUI.subMenuOpen = false;
            this.dispose();
        }

        if (o.equals(rad_InsideArea)) {
            rad_OutsideArea.setSelected(false);
        }
        if (o.equals(rad_OutsideArea)) {
            rad_InsideArea.setSelected(false);
        }

        if (o.equals(btn_AddArea)) {
            if (cbo_AreaSelect.getSelectedItem().equals("None...")) {
                return;
            }
            if (!rad_InsideArea.isSelected() && !rad_OutsideArea.isSelected()) {
                return;
            }
            Vars.Area wa = ScriptManager.getArea(cbo_AreaSelect.getSelectedIndex());
            if (wa == null) {
                System.out.println("Fucking Shit!");
            }
            ScriptManager.addTask(new Condition.Area(wa.getArea(), rad_InsideArea.isSelected(), chx_RepeatLastTask.isSelected()));
            if (rad_InsideArea.isSelected())
                SetupUI.taskListModel.addElement("[COND] <Area> " + wa.getName() + " - Inside of the Area");
            else
                SetupUI.taskListModel.addElement("[COND] <Area> " + wa.getName() + " - Outside of the Area");

            SetupUI.list_Tasks.updateUI();
            SetupUI.subMenuOpen = false;
            this.dispose();
        }

        if (o.equals(btn_InvFull)) {
            ScriptManager.addTask(new Condition.Inventory(0, chx_RepeatLastTask.isSelected()));
            SetupUI.taskListModel.addElement("[COND] <Inv> Full");
            SetupUI.list_Tasks.updateUI();
            SetupUI.subMenuOpen = false;
            this.dispose();
        }

        if (o.equals(btn_InvEmpty)) {
            ScriptManager.addTask(new Condition.Inventory(1, chx_RepeatLastTask.isSelected()));
            SetupUI.taskListModel.addElement("[COND] <Inv> Empty");
            SetupUI.list_Tasks.updateUI();
            SetupUI.subMenuOpen = false;
            this.dispose();
        }

        if (o.equals(btn_AddInvMiss)) {
            ScriptManager.addTask(new Condition.Inventory(in_InvMissItemName.getText(), chx_RepeatLastTask.isSelected()));
            SetupUI.taskListModel.addElement("[COND] <Inv> Item Missing: " + in_InvMissItemName.getText());
            SetupUI.list_Tasks.updateUI();
            SetupUI.subMenuOpen = false;
            this.dispose();
        }
        if (o.equals(btn_AddInvAmt)) {
            ScriptManager.addTask(new Condition.Inventory(in_InvAmtName.getText(), Integer.parseInt(in_InvAmtQuantity.getText()), chx_RepeatLastTask.isSelected()));
            SetupUI.taskListModel.addElement("[COND] <Inv> Item Quantity: " + in_InvAmtQuantity.getText() + " x " + in_InvAmtName.getText());
            SetupUI.list_Tasks.updateUI();
            SetupUI.subMenuOpen = false;
            this.dispose();
        }

        if (o.equals(rad_InterfaceOpen)) {
            rad_InterfaceClosed.setSelected(false);
        } else if (o.equals(rad_InterfaceClosed)) {
            rad_InterfaceOpen.setSelected(false);
        }

        if (o.equals(btn_InterfaceCurrent)) {
            in_InterfaceId.setText("" + c.widgets.getOpenInterfaceId() + " - " + c.widgets.getBackDialogId());
        }

        if (o.equals(btn_AddInterface)) {

            if (in_InterfaceId.getText().isEmpty() || (!rad_InterfaceOpen.isSelected() && !rad_InterfaceClosed.isSelected())) {
                System.out.println("Here!");
                return;
            }

            int main = Integer.parseInt(in_InterfaceId.getText().split(" - ")[0]);
            int chat = Integer.parseInt(in_InterfaceId.getText().split(" - ")[1]);
            ScriptManager.addTask(new Condition.Interface(main, chat, rad_InterfaceOpen.isSelected() , chx_RepeatLastTask.isSelected()));
            if (rad_InterfaceOpen.isSelected()) {
                SetupUI.taskListModel.addElement("[COND] <Int> " + main + " | " + chat + " - Is Open - RepLast: " + chx_RepeatLastTask.isSelected());
            } else {
                SetupUI.taskListModel.addElement("[COND] <Int> " + main + " | " + chat + " - Is Closed - RepLast: " + chx_RepeatLastTask.isSelected());
            }
        }
    }
    // End of variables declaration//GEN-END:variables
}
