/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.unix.slayer.setup.A;

import org.unix.slayer.Constants;
import org.unix.slayer.setup.B.B_Tasks;
import org.unix.slayer.setup.SetupConfig;
import org.unix.slayer.setup.SetupManager;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileFilter;


/**
 *
 * @author 0x181
 */
public class A_Presets extends JFrame implements ActionListener {

    /**
     * Creates new form A_Presets
     */
    public A_Presets() {
        setLocationRelativeTo(null);
        initComponents();
    }

    public boolean newPresetWindowOpen = false;
    public static boolean tasksWindowOpen = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        combi_Preset = new JComboBox<>();
        jLabel4 = new JLabel();
        btn_AddNew = new JButton();
        btn_AddNew.addActionListener(this);
        btn_Next = new JButton();
        btn_Next.addActionListener(this);
        combi_Preset_Model = new DefaultComboBoxModel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Welcome to the uSlayer setup...");

        jLabel2.setText("Please select a Preset to continue.");

        jLabel3.setText("Preset");

        combi_Preset.setModel(combi_Preset_Model);

        jLabel4.setText("If you have no presets then create a new one!");

        btn_AddNew.setText("Create New Preset");
        btn_AddNew.addActionListener(this);

        btn_Next.setText("Next");
        btn_Next.addActionListener(this);

        File file = new File(Constants.USER_DIR + "/presets/");
        if (!file.exists()) { file.mkdirs(); }
        File[] files = file.listFiles(new FileFilter() {
            @Override
            public boolean accept(File f) {
                return f.isDirectory();
            }
        });
        if (files.length > 0) {
            for (File f : files) {
                combi_Preset.addItem(f.getName());
            }
        }
        combi_Preset.updateUI();

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel4)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addComponent(jLabel3)
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(combi_Preset, GroupLayout.PREFERRED_SIZE, 134, GroupLayout.PREFERRED_SIZE))))
                                        .addComponent(btn_AddNew))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Next)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel4)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(combi_Preset, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btn_AddNew, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                .addComponent(btn_Next, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    public void addPreset(String presetName) {
        combi_Preset.addItem(presetName);
        combi_Preset.setSelectedItem(presetName);
        combi_Preset.updateUI();
        SetupManager.createNewConfig(presetName);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btn_AddNew;
    private JButton btn_Next;
    private JComboBox<String> combi_Preset;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private DefaultComboBoxModel combi_Preset_Model;

    @Override
    public void actionPerformed(ActionEvent e) {
        Object s = e.getSource();
        if (s.equals(btn_AddNew)) {
            if (!newPresetWindowOpen) {
                newPresetWindowOpen = true;
                new NewPreset(this).setVisible(true);
            }
            return;
        } else if (s.equals(btn_Next)) {
            if (!tasksWindowOpen) {
                SetupManager.currentConfig = SetupManager.getTotalList().get(combi_Preset.getSelectedIndex());
                this.dispose();
                new B_Tasks().setVisible(true);
                tasksWindowOpen = true;
            }
        }
    }
    // End of variables declaration//GEN-END:variables
}
