/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.unix.script.ui;

import org.unix.script.manager.ScriptManager;
import org.unix.script.tasks.Task;
import org.unix.script.uScript;
import simple.api.script.Script;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author 0x181
 */
public class SetupUI extends javax.swing.JFrame implements ActionListener {

    public static void main(String... args) {
        ScriptManager s = new ScriptManager();
        new SetupUI().setVisible(true);
    }


    public static boolean subMenuOpen = false;

    public static DefaultListModel taskListModel;

    /**
     * Creates new form SetupUI
     */
    public SetupUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_Tasks = new javax.swing.JList<>();
        btn_ListUp = new javax.swing.JButton();
        btn_ListDown = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        btn_ListDelete = new javax.swing.JButton();
        btn_Int_Obj = new javax.swing.JButton();
        btn_Int_Npc = new javax.swing.JButton();
        btn_Int_Item = new javax.swing.JButton();
        btn_Move = new javax.swing.JButton();
        btn_Teleport = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        btn_Bank = new javax.swing.JButton();
        btn_Shop = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        btn_Vars = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        btn_Save = new javax.swing.JButton();
        btn_Load = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        btn_Start = new javax.swing.JButton();
        btn_Sleep = new javax.swing.JButton();
        btn_Condition = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_ScriptName = new javax.swing.JTextField();
        txt_ScriptAuthor = new javax.swing.JTextField();
        taskListModel = new DefaultListModel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        setTitle("uScript - Making Scripting... Simple!");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Welcome to uScript");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        list_Tasks.setModel(taskListModel);

        jScrollPane1.setViewportView(list_Tasks);

        btn_ListUp.setText("UP");
        btn_ListUp.addActionListener(this);

        btn_ListDown.setText("DOWN");
        btn_ListDown.addActionListener(this);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btn_ListDelete.setText("Delete");
        btn_ListDelete.addActionListener(this);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1)
                                .addContainerGap())
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(btn_ListUp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_ListDown)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_ListDelete)
                                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(btn_ListUp)
                                                .addComponent(btn_ListDown))
                                        .addComponent(btn_ListDelete))
                                .addContainerGap())
        );

        btn_Int_Obj.setText("Interact With Object");
        btn_Int_Obj.addActionListener(this);

        btn_Int_Npc.setText("Interact With NPC");
        btn_Int_Npc.addActionListener(this);

        btn_Int_Item.setText("Interact With Item");
        btn_Int_Item.addActionListener(this);

        btn_Move.setText("Move");
        btn_Move.addActionListener(this);

        btn_Teleport.setText("Teleport");
        btn_Teleport.addActionListener(this);

        btn_Bank.setText("Banking");
        btn_Bank.addActionListener(this);

        btn_Shop.setText("Shops");
        btn_Shop.addActionListener(this);

        btn_Vars.setText("Edit Script Variables");
        btn_Vars.addActionListener(this);

        btn_Save.setText("Save to File");
        btn_Save.addActionListener(this);

        btn_Load.setText("Load from File");
        btn_Load.addActionListener(this);

        btn_Start.setText("Start Script");
        btn_Start.addActionListener(this);

        btn_Sleep.setText("Sleep");
        btn_Sleep.addActionListener(this);

        btn_Condition.setText("Condition");
        btn_Condition.addActionListener(this);

        jLabel2.setText("Script Name:");

        jLabel3.setText("Script Author:");

        txt_ScriptName.setEditable(false);
        txt_ScriptName.setToolTipText("Visit Script Vars to set this");
        txt_ScriptName.setText("");

        txt_ScriptAuthor.setEditable(false);
        txt_ScriptAuthor.setText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(btn_Int_Obj, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                                        .addComponent(btn_Int_Npc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btn_Int_Item, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btn_Move, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btn_Teleport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jSeparator2)
                                                        .addComponent(jSeparator1)
                                                        .addComponent(btn_Bank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btn_Shop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jSeparator3)
                                                        .addComponent(btn_Vars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jSeparator4)
                                                        .addComponent(btn_Save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btn_Load, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jSeparator6)
                                                        .addComponent(btn_Start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btn_Sleep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btn_Condition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txt_ScriptName, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                                        .addComponent(txt_ScriptAuthor))))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(txt_ScriptName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(txt_ScriptAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btn_Int_Obj)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_Int_Npc)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_Int_Item)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_Move)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_Teleport)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_Bank)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_Shop)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_Sleep)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btn_Condition)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_Vars)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_Save)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_Load)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_Start))
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Bank;
    private javax.swing.JButton btn_Condition;
    private javax.swing.JButton btn_Int_Item;
    private javax.swing.JButton btn_Int_Npc;
    private javax.swing.JButton btn_Int_Obj;
    private javax.swing.JButton btn_ListDelete;
    private javax.swing.JButton btn_ListDown;
    private javax.swing.JButton btn_ListUp;
    private javax.swing.JButton btn_Load;
    private javax.swing.JButton btn_Move;
    private javax.swing.JButton btn_Save;
    private javax.swing.JButton btn_Shop;
    private javax.swing.JButton btn_Sleep;
    private javax.swing.JButton btn_Start;
    private javax.swing.JButton btn_Teleport;
    private javax.swing.JButton btn_Vars;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    public static javax.swing.JList<String> list_Tasks;
    public static javax.swing.JTextField txt_ScriptAuthor;
    public static javax.swing.JTextField txt_ScriptName;

    @Override
    public void actionPerformed(ActionEvent e) {
        Object o = e.getSource();

        if (subMenuOpen) {
            return;
        }

        if (o.equals(btn_Int_Npc)) {
            new ui_IntNpc().setVisible(true);
            subMenuOpen = true;
        }
        if (o.equals(btn_Int_Obj)) {
            new ui_IntObj().setVisible(true);
            subMenuOpen = true;
        }
        if (o.equals(btn_Int_Item)) {
            new ui_IntItem().setVisible(true);
            subMenuOpen = true;
        }

        if (o.equals(btn_Move)) {
            new ui_Move().setVisible(true);
        }
        if (o.equals(btn_Teleport)) {
            new ui_Teleport().setVisible(true);
        }

        if (o.equals(btn_Bank)) {
            new ui_Banking().setVisible(true);
        }
        if (o.equals(btn_Shop)) {
            new ui_Shops().setVisible(true);
        }

        if (o.equals(btn_Sleep)) {
            new ui_Sleep().setVisible(true);
        }
        if (o.equals(btn_Condition)) {
            new ui_Conditional().setVisible(true);
        }
        if (o.equals(btn_Vars)) {
            new ui_ScriptVars().setVisible(true);
        }

        if (o.equals(btn_Save)) {

        }
        if (o.equals(btn_Load)) {

        }

        if (o.equals(btn_Start)) {
            for (Task t : ScriptManager.list) {
                System.out.println(t.getUIOutput());
            }
            ScriptManager.startScript();
            uScript.RunScript = true;
        }


        // list buttons
        if (o.equals(btn_ListUp)) {

        }

        if (o.equals(btn_ListDown)) {

        }

        if (o.equals(btn_ListDelete)) {
            if (list_Tasks.getSelectedIndex() == -1) { return; }
            ScriptManager.removeTask(list_Tasks.getSelectedIndex());
            taskListModel.remove(list_Tasks.getSelectedIndex());
            list_Tasks.updateUI();
        }
    }
    // End of variables declaration//GEN-END:variables
}
