/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.unix.utility.path;

import net.runelite.api.coords.WorldPoint;
import simple.robot.api.ClientContext;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 *
 * @author 0x181
 */
public class PathGen extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form PathGen
     */
    public PathGen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txt_Total = new javax.swing.JLabel();
        btn_Add = new javax.swing.JButton();
        btn_Del = new javax.swing.JButton();
        btn_Gen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Out = new javax.swing.JTextArea();
        txt_Out.setLineWrap(true);
        pathList = new ArrayList<>();


        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Path Generator");
        setResizable(false);
        setAlwaysOnTop(true);

        jLabel1.setText("Welcome to the Path Generator");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt_Total.setText("Total Tiles in Paths:");

        btn_Add.setText("Add Current");
        btn_Add.addActionListener(this);

        btn_Del.setText("Remove Last");
        btn_Del.addActionListener(this);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txt_Total)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_Add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(btn_Del)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Add)
                    .addComponent(btn_Del))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_Total)
                .addContainerGap())
        );

        btn_Gen.setText("Generate");
        btn_Gen.addActionListener(this);

        txt_Out.setColumns(20);
        txt_Out.setRows(5);
        jScrollPane1.setViewportView(txt_Out);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_Gen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_Gen)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_Del;
    private javax.swing.JButton btn_Gen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt_Out;
    private javax.swing.JLabel txt_Total;
    private ArrayList<String> pathList;

    @Override
    public void actionPerformed(ActionEvent e) {
        Object o = e.getSource();
        ClientContext c = ClientContext.instance();
        WorldPoint loc = c.players.getLocal().getLocation();
        if (o.equals(btn_Add)) {
            pathList.add("" + loc.getX() + ", " + loc.getY() + ", " + loc.getPlane());
            System.out.println(pathList.get(pathList.size()-1));
        } else if (o.equals(btn_Del)) {
            pathList.remove(pathList.size()-1);
        } else if (o.equals(btn_Gen)) {
            txt_Out.setText("public WorldPoint[] path = new WorldPoint[] {");
            for (int i = 0; i < pathList.size(); i++) {
                txt_Out.setText(txt_Out.getText() + "\n\tnew WorldPoint(" + pathList.get(i) + "),");
            }
            txt_Out.setText(txt_Out.getText() + "\n };");

        }

        txt_Total.setText("Total Tiles in Paths:" + pathList.size());
    }
}
